language: php

php:
    - 5.6
    - 7.0
    - hhvm

before_script:
    - travis_retry composer self-update
    - composer update --prefer-stable --no-interaction

script:
    - ./bin/phpunit --coverage-text --verbose
    - ./bin/phpcs --standard=PSR2 src tests
