language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

before_script:
    - composer install --prefer-source

script:
    - ./bin/phpunit --coverage-text --verbose
    - ./bin/phpcs --standard=PSR2 src tests
